CREATE TABLE usuarios (
usuario_dni VARCHAR(18) PRIMARY KEY,
primer_nombre VARCHAR(20) NOT NULL,
segundo_nombre VARCHAR(20),
primer_apellido VARCHAR(20) NOT NULL,
segundo_apellido VARCHAR(20),
email VARCHAR(50) NOT NULL UNIQUE,
fecha_registro DATETIME DEFAULT CURRENT_TIMESTAMP,
salario DECIMAL(8,2) NOT NULL,
estado BOOLEAN DEFAULT TRUE,
creado_por VARCHAR(100) NOT NULL,
creado_en DATETIME DEFAULT CURRENT_TIMESTAMP,
modificado_por VARCHAR(100),
modificado_en DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);