enum estado__t {
	activo
	cerrado
	borrador
}

enum tipo__t {
	ingreso
	gasto
	ahorro
}

enum metodo_pago__t {
	efectivo
	tarjeta_debito
	tarjeta_credito
	transferencia
}

Table usuarios [headercolor: #175e7a] {
	usuario_dni varchar(18) [ pk, not null ]
	primer_nombre varchar(20) [ not null ]
	segundo_nombre varchar(20)
	primer_apellido varchar(20) [ not null ]
	segundo_apellido varchar(20)
	email varchar(50) [ not null, unique ]
	fecha_registro datetime [ default: CURRENT_TIMESTAMP ]
	salario decimal(8,2) [ not null ]
	estado boolean [ default: true ]
	creado_por varchar(100) [ not null ]
	creado_en datetime [ default: CURRENT_TIMESTAMP ]
	modificado_por varchar(100)
	modificado_en datetime [ default: CURRENT_TIMESTAMP ]
}

Table presupuestos [headercolor: #175e7a] {
	id_presupuesto integer [ pk, increment, not null ]
	usuario_dni varchar(18) [ not null ]
	nombre varchar(40) [ not null ]
	descripcion varchar(200)
	anio_inicio mediumint [ not null ]
	mes_inicio tinyint [ not null ]
	anio_fin mediumint [ not null ]
	mes_fin tinyint [ not null ]
	total_ingresos decimal(8,2) [ not null, default: 0 ]
	total_gastos decimal(8,2) [ not null, default: 0 ]
	total_ahorro decimal(8,2) [ not null, default: 0 ]
	fecha_creacion datetime [ default: CURRENT_TIMESTAMP ]
	estado estado__t [ not null, default: borrador ]
	creado_por varchar(100) [ not null ]
	creado_en datetime [ default: CURRENT_TIMESTAMP ]
	modificado_por varchar(100)
	modificado_en datetime [ default: CURRENT_TIMESTAMP ]
}

Table categorias [headercolor: #175e7a] {
	id_categoria integer [ pk, increment, not null ]
	nombre varchar(50) [ not null ]
	descripcion varchar(250)
	tipo tipo__t [ not null ]
	icono_nombre varchar(250)
	color_hex varchar(50)
	orden integer
	creado_por varchar(100) [ not null ]
	creado_en datetime [ default: CURRENT_TIMESTAMP ]
	modificado_por varchar(100)
	modificado_en datetime [ default: CURRENT_TIMESTAMP ]
}

Table subcategorias [headercolor: #175e7a] {
	id_subcategoria integer [ pk, increment, not null ]
	id_categoria integer [ not null ]
	nombre varchar(50) [ not null ]
	descripcion varchar(255)
	estado boolean [ default: true ]
	por_defecto boolean [ default: false ]
	creado_por varchar(100) [ not null ]
	creado_en datetime [ default: CURRENT_TIMESTAMP ]
	modificado_por varchar(100)
	modificado_en datetime [ default: CURRENT_TIMESTAMP ]
}

Table presupuestos_detalles [headercolor: #175e7a] {
	id_pdetalle integer [ pk, increment, not null ]
	id_presupuesto integer [ not null ]
	id_subcategoria integer [ not null ]
	monto_asignado decimal(8,2) [ not null ]
	justificacion_monto varchar(255)
	creado_por varchar(100) [ not null ]
	creado_en datetime [ default: CURRENT_TIMESTAMP ]
	modificado_por varchar(100)
	modificado_en datetime [ default: CURRENT_TIMESTAMP ]
}

Table obligaciones_fijas [headercolor: #175e7a] {
	id_obligacion integer [ pk, increment, not null ]
	usuario_dni varchar(18) [ not null ]
	id_subcategoria integer [ not null ]
	nombre varchar(50) [ not null ]
	descripcion varchar(255)
	monto_fijo decimal(8,2) [ not null ]
	vence_dia tinyint [ not null ]
	vigente boolean [ default: true ]
	fecha_inicio date [ not null ]
	fecha_final date
	creado_por varchar(100) [ not null ]
	creado_en datetime [ default: CURRENT_TIMESTAMP ]
	modificado_por varchar(100)
	modificado_en datetime [ default: CURRENT_TIMESTAMP ]
}

Table transacciones [headercolor: #175e7a] {
	id_transaccion integer [ pk, increment, not null ]
	usuario_dni varchar(18) [ not null ]
	id_presupuesto integer [ not null ]
	anio mediumint [ not null ]
	mes tinyint [ not null ]
	id_subcategoria integer [ not null ]
	tipo tipo__t [ not null ]
	descripcion varchar(255)
	monto decimal(8,2) [ not null ]
	fecha_ocurrido datetime [ not null ]
	metodo_pago metodo_pago__t [ not null ]
	num_factura varchar(20)
	observaciones varchar(255)
	fecha_registro datetime [ default: CURRENT_TIMESTAMP ]
	creado_por varchar(100) [ not null ]
	creado_en datetime [ default: CURRENT_TIMESTAMP ]
	modificado_por varchar(100)
	modificado_en datetime [ default: CURRENT_TIMESTAMP ]
}

Table obligaciones_transaccion [headercolor: #175e7a] {
	id_transaccion integer [ not null ]
	id_obligacion integer [ not null ]

	indexes {
		(id_transaccion, id_obligacion)
	}
}

Ref fk_presupuestos_usuario_dni_usuarios {
	presupuestos.usuario_dni > usuarios.usuario_dni [ delete: no action, update: no action ]
}

Ref fk_obligaciones_fijas_usuario_dni_usuarios {
	obligaciones_fijas.usuario_dni > usuarios.usuario_dni [ delete: no action, update: no action ]
}

Ref fk_transacciones_usuario_dni_usuarios {
	transacciones.usuario_dni > usuarios.usuario_dni [ delete: no action, update: no action ]
}

Ref fk_subcategorias_id_categoria_categorias {
	subcategorias.id_categoria > categorias.id_categoria [ delete: no action, update: no action ]
}

Ref fk_presupuestos_detalles_id_subcategoria_subcategorias {
	presupuestos_detalles.id_subcategoria > subcategorias.id_subcategoria [ delete: no action, update: no action ]
}

Ref fk_obligaciones_fijas_id_subcategoria_subcategorias {
	obligaciones_fijas.id_subcategoria > subcategorias.id_subcategoria [ delete: no action, update: no action ]
}

Ref fk_transacciones_id_subcategoria_subcategorias {
	transacciones.id_subcategoria > subcategorias.id_subcategoria [ delete: no action, update: no action ]
}

Ref fk_presupuestos_detalles_id_presupuesto_presupuestos {
	presupuestos_detalles.id_presupuesto > presupuestos.id_presupuesto [ delete: no action, update: no action ]
}

Ref fk_transacciones_id_presupuesto_presupuestos {
	transacciones.id_presupuesto > presupuestos.id_presupuesto [ delete: no action, update: no action ]
}

Ref fk_obligaciones_transaccion_id_transaccion_transacciones {
	obligaciones_transaccion.id_transaccion - transacciones.id_transaccion [ delete: no action, update: no action ]
}

Ref fk_obligaciones_transaccion_id_obligacion_obligaciones_fijas {
	obligaciones_transaccion.id_obligacion < obligaciones_fijas.id_obligacion [ delete: no action, update: no action ]
}